### ISSUE TITLE
Server crash on Player Join

### ISSUE THREAD

**Issue by APolarBaer** [darkevilmac/archimedes-ships-plus#105]
http://pastebin.com/3Fv8Ypyq

**Comment by darkevilmac** [comment]
Could I get a copy of the full latest log from the server as well as the client that crashes?

**Comment by exaskye** [comment]
https://github.com/elytra/DavincisVessels/blob/1.10/src/main/java/io/github/elytra/davincisvessels/common/handler/ConnectionHandler.java#L62-L71

Sending packets in a log-out event is illegal, as the nethandler may have been destroyed. Your packet would never be received by the client anyway. The NPE is in LambaNetwork (hence why I was interested and replied) due to the nethandler being null.

**Comment by APolarBaer** [comment]
Idk how but ive updated everything in the pack and it seems to be fine now, including your mod and moving worlds. but here anyways, also it was just the server that crashed:
[fml-server-1 - Copy.txt](https://github.com/elytra/DavincisVessels/files/595430/fml-server-1.-.Copy.txt)

**Comment by exaskye** [comment]
It's likely the bug isn't actually fixed, and you just aren't getting it now, as it seems to be a race condition.

**Comment by APolarBaer** [comment]
ill post here again if i come across it then

**Comment by darkevilmac** [comment]
> Sending packets in a log-out event is illegal, as the nethandler may have been destroyed. Your packet would never be received by the client anyway.

The more you know, I'll change it so the config is reset by the client.
