### ISSUE TITLE
Bug investigation of minecraft1.10.2:davincisvessels-1.10.2-0006-full

### ISSUE THREAD

**Issue by karikusa** [darkevilmac/archimedes-ships-plus#135]
It was examined whether there wasn't a bug using davincisvessels-1.10.2-0006-full of minecraft1.10.2.
There may be also report finish already, but....
Even if I crash and moreover I log in when blocking made with 1 and chiselsandbits-12.12 is assembled, blackly, all except for indication of an item slot and map MOD crashes once again. It couldn't be restored.
After mount release, the location of ItemRack of 2 and TConstruct-1.10.2-2.6.3 changes to the north.
When 3, an architrave of vanilla and a painting make a ship behind the mount move, it comes off.
When 4 and protection building make a ship behind the mount move, it falls.
When I do a mount after blocking and assembly as 5 and ShoreBuffer and move, a part facing the ship follows for 1 block.

Anyway it's nice MOD, so it'll be pleasant for future, won't it?

**Comment by karikusa** [comment]
After that, there was a phenomenon that the extraction surface of the StorageDrawers - 1.10.2 - 3.6.1 additionally faced east after mounting.

Postscript: Material Transport Airship is not too cool! Is it?

**Comment by exaskye** [comment]
I can barely understand this issue. Sorry.

Please post a crash report with [Gist](https://gist.github.com) if you have one, otherwise, post the logs from `~/.minecraft/logs/fml-client-latest.log`.

Rotating blocks (item racks from TConstruct, drawers from StorageDrawers) are pretty much to be expected, unfortunately.

Paintings are entities, not blocks, so they can't be carried with ships.

Davinci's is not compatible with protection plugins.

**Comment by darkevilmac** [comment]
Closing this issue due to a lack of response from the original poster.
