### ISSUE TITLE
Is archimedes ships plus intended to be compatible?

### ISSUE THREAD

**Issue by ajrb** [darkevilmac/archimedes-ships-plus#14]
Is this continuation of the archimedes ships mod intended to be backwards compatible with the original mod? If so, this issue is a bug, if not it's just a question. (I tried to add a label, but I cannot figure out how to - I can sort by labels or query by labels but no idea how to add a label to this issue, sorry just spent 15 minutes trying. Are you sure you're not the only one with permission to label?)

When I tried upgrading to plus, I got the message that my world contained missing blocks (the old archimedes mod blocks) so I aborted since I have a lot of ships I don't want to lose. My guess is this is probably that block ids have changed?

**Comment by darkevilmac** [comment]
Unfortunately I don't plan on having compatibility between the mods. The main reason behind this is one because the mod has a different id and name. So forge treats them as such, the other reason behind this is with the amount of things I've changed  it would be very difficult to keep compatibility between the mods.
