### ISSUE TITLE
Ship flickering in and out of screen while mounted

### ISSUE THREAD

**Issue by andrewoberson** [darkevilmac/archimedes-ships-plus#227]
While mounting a sea vessel, the rendered ship disappears as i look around.

Minecraft 1.12.2 
Vessels 6.340
Moving World 6.342  
Forge 12.23.2.2611

**Comment by Lurmey** [comment]
I don't think this is a bug with Davinci's Vessels. It's an issue in the vanilla game; entities derender when their centre is out of view of the player. So even if you could still see the edge of the entity, it'll disappear as soon as the centre is out of view. You don't notice this in the vanilla game because most entities are too small for the effect to really show, except perhaps ghasts, the Wither or the Ender Dragon.

**Comment by darkevilmac** [comment]
As mentioned by Lurmey, this is a vanilla bug. I've looked into it and the only way I could find to fix it would involve fucking around with vanilla's entity culling and I'm really not into that idea.
