### ISSUE TITLE
Fuel diapering in Steam Engine.

### ISSUE THREAD

**Issue by bedrockbusters** [darkevilmac/archimedes-ships-plus#342]
- The version of the mod you are using 6.340 Full
- Your Minecraft version 1.12.2
- Your Forge version 14.23.5.285
Whenever I put fuel, say coal wood lava bucket, into the engine and assemble the ship, then disassemble the ship, it clears the inventory of the steam engines.

**Comment by darkevilmac** [comment]
Been a while since I've worked on the codebase unfortunately, but if I recall correctly the way the engine works is when you start your ship it consumes all of the fuel that was added at once and then begins ticking down that variable as you fly.

So your fuel is still getting used, even if it seems like it just disappeared.

This is something that will be made more clear in 1.16
