### ISSUE TITLE
Ship not assembling

### ISSUE THREAD

**Issue by austanss** [darkevilmac/archimedes-ships-plus#356]
I have an issue, similar to another, that when I attempt to assemble a ship it just hangs and does nothing.

Some info:
Mod version: 1.12-6.340
Forge version: 14.23.5.2854
Minecraft version: 1.12.2
Java version: 1.8
OS: Linux 5.8

I'm using the Terra 1:1 mod with Cubic Chunks, and I have a serious issue.

I can't assemble my submarine, it just hangs.

It is a singleplayer world. My build consists of leaves. planks, cobble, crafting table, furnace, doors, and torches.

It is dire because my current Y level is -4930, AKA the bottom of the Atlantic. If I die I cannot reach back to this point to recover my valuables.

It was assembling before and then it just stopped working. I built a structure around it to keep it out of the water, as I thought that was the issue, but it wasn't. The ground is made of blacklisted blocks...

I checked the Minecraft logs and found no errors except a few initialization warnings about DV items being registered with the `minecraft` tag.

Could this be the issue? I dunno.

**Comment by JoeMamasMama** [comment]
Exactly same issue and same mods here, I disassembled at the location of the challenger deep, it was in the Y level of -10000 and then I couldn't assemble it again, it just showed "Assembling...".
I think that the mod just starts breaking when reaching a height that is too low or maybe it's just the Cubic Chunks messing around with it, I hope it can be fixed in the future.

**Comment by austanss** [comment]
Kind of disappointing to see no progress after a year of the issue being open.
