### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by darkevilmac** [darkevilmac/archimedes-ships-plus#4]
I'm just going to leave this here so everyone knows why features aren't going to be implemented super fast right now. Currently, I'm working on changing the way ships are formed as well as separating code related to tile entities and such into a library. This way the actual mod can simply hold information about how to move ships, where to move them, when to move them, who can move them, etc. This will take some time and if I choose a set date I can guarantee I won't make it at that time. So for now it'll be done "Soon™"

**Comment by lucom** [comment]
I always appreciate refactoring old code to prepare it for new requirements!
Good to hear that you are actively improving the code quality.

**Comment by melekaiah** [comment]
very much looking forwards to see what you do. 
When you are ready to start adding or changeing things. i may be able to help with some blocks/textures.

**Comment by darkevilmac** [comment]
Update: All code has been moved, most code is working, all that needs to be done now is adding back seats, and engines. Then bugtesting.

**Comment by jdmiller82** [comment]
Glad you're leading the charge with this mod. I look forward to following your progress.

**Comment by Alaberti** [comment]
Are you still looking for help, and how can we help you?

**Comment by darkevilmac** [comment]
@Alaberti Read the project readme, if you are interested in being a long term dev of the mod with me then please give me a direct message on the minecraft forums as to what you're interested in doing.

**Comment by darkevilmac** [comment]
Complete.

**Comment by CPDXD101** [comment]
okay i am quoting a suggestion from someone who has yet to put it in the github (from Luvatar)
the quote is:
This mod is actually my favorite addition to Terrafirma, which has so much "traveling" into it that having a move-able base is wonderful. I'm sure that making two mods work together is much more hassle than what is typically requested of modders, but I still want to make this request because Terrafirma and Archimedes ships are just so wonderful together. 

Here are some of the issues I've found:

- A lot of blocks don't stay oriented the same way after landing. Chests, Fence Gates, Chiseled blocks, planks, etc. This isn't an issue with carpenter's blocks blocks, so I don't know why it's different.

- Every time I board the ship I get an "oak" duplicate of any chest/barrel that is on the ship. This is mostly an annoyance.

- It seems that non-vanilla entities don't get transported in the crates. This was a huge letdown after having seeing it work before :/ EDIT: Actually I just tested it a bit and it seems to not be terra-firma related but rather something to do with being underwater when the ship is formed. As the ship formed the mobs floated for a milisecond, that caused them to be "moved" out of the crate it seems. Just managed to move some non-vanilla entities :)

- There is a weird major bug involving a chisseled block with a Lantern and an adjasent fence post that makes the entire display go bonkers for anyone within sight of the ship. (No crash, but game is unplayable). I had to exit the world and delete the mod blocks by myself to make the chunks around the ship usable again. This is a very obscure bug to replicate but I mostly suspect it has something to do with the chisseled blocks bug. 

As for non-Terrafirma related requests I have 2:

- Maybe make a special Bed that won't break your spawn point if you move the ship. We like to make the ship a mobile base and having someone die just to re-spawn at the world spawn point instead of at the ship because he forgot to re-sleep after moving it is annoying.

- Maybe add a special ship helm and buffers for "Sub-ships". Our big, floating base can realistically only land on Water, and when we are in the middle of a large land-mass, we like to leave it floating high and use smaller ships to land. Currently the only way of doing this is destroying the blocks anchoring both the Mother ship and the smaller one, or use an elaborate piston design to do that for us. I mean, the pistol design is kind of cool, but having core-mod options for that would be neat. 


Also, not so much a bug report but something that I'd like to understand from the mod. Our ship "beta" design floated pretty decently while it was on its ugly form. However, once we changed the outer blocks for stairs to give it a more defined curve it seems like it lost bouyancy, a lot. I'm unsure if it was because it was carpenters block stairs or simply because stairs dont count as well for the bouyancy, but it made us add a ton of floaters to keep it on the level it was before.
