### ISSUE TITLE
assembly leaving water void, incomplete assembly, disappearing boat

### ISSUE THREAD

**Issue by Zeph0s** [darkevilmac/archimedes-ships-plus#40]
Updated my server from 1.7.2 with the old Archimedes mod. Placed the new helm block on my boat and assembled. The boat assembled OK, except it left a void in the water where its blocks used to be. Basically I was stuck in a pit in the middle of the water.

Disassembled, then reassembled. The boat assembled again, except this time the blocks of the ship that were to the right and behind the helm stayed as static blocks. Couldn't disassemble because of the static blocks in the way, and couldn't move the boat out of the way because the pit in the water was created again and the boat was stuck.

I dismounted the boat. The boat shot off in the opposite direction at about 20 m/s and disappeared once it was a couple chunks away.

:(

**Comment by darkevilmac** [comment]
FML Server Latest Log.

**Comment by Zeph0s** [comment]
http://hastebin.com/ocewezisiz.vala

**Comment by darkevilmac** [comment]
Reread the issue I misunderstood, this is a known issue, it's a matter of the way assembly works (it doesn't know water blocks that it never saw exist existed.) build your stuff on top of the water not in the water.

**Comment by ent1119** [comment]
> Reread the issue I misunderstood, this is a known issue, it's a matter of the way assembly works (it doesn't know water blocks that it never saw exist existed.) build your stuff on top of the water not in the water.

the problem is that, currently rejoining a world after leaving a ship spawned somehow despawns it.
(it's also how I lost my mercury brig)
so disassembling a ship before leaving is essential, next spawn however it leaves a void in the water.


a solution to the water void problem IMO would be; when a ship assembles, the squared area of the ship's construction zone and find the water level for the set world. 
after it finds the set water level it fills all available space (let's say 63 {standard} is the water level) under 63 where the build was built, making dissembling and assembling not leave water voids.

there might be a small problem with that if you're underground lower then set water level, however it could also search for chunk biome (for example, if the constructed ship is in biome "ocean" or "river", it will fill water level, if in "plains", or idk, "forest", it will not fill.
