### ISSUE TITLE
Ship graphical glitch  

### ISSUE THREAD

**Issue by RandallBoxwood7** [darkevilmac/archimedes-ships-plus#56]
Whenever I enter any kind of vehicle and use it  whether it be a sub, boat, or airship the vehicle model flickers from being invisible and visible, I do not experience a crash but it severely impacts gameplay.

**Comment by darkevilmac** [comment]
Known bug, not sure why there's not an issue for it. More of a movingworld issue but I'll leave it here anyways. It's due to the 1.8 rendering engine not thinking the ship is in range due to it's size and collision and all that. Just a matter of overriding when Minecraft thinks it needs to render it, most likely the best way to achieve that is to force rendering no matter what.
