### ISSUE TITLE
1.7.10 - V1.8.1 Ship feature request

### ISSUE THREAD

**Issue by mandm635** [darkevilmac/archimedes-ships-plus#83]
I have been messing around with the water ships, and I think it would be a good idea to fill the water when assembling with water instead of air. My ship just gets stuck in the current after I assemble it again.

**Comment by splifcad** [comment]
unless another dev wants to take up the issue,  i'm retty sure it has been stated that 1.9+ will be the primary focus of all future development.

I for one as a server admin don't want to waste time, and would rather develop for the current state of the game so that it can be open to the broadest user-base possible.

**Comment by darkevilmac** [comment]
> unless another dev wants to take up the issue, i'm pretty sure it has been stated that 1.9+ will be the primary focus of all future development.
> 
> I for one as a server admin don't want to waste time, and would rather develop for the current state of the game so that it can be open to the broadest user-base possible.

Unfortunately 1.9 doesn't currently have a stable build so I'll be sticking to 1.8.9 while I update to 1.9 as well. I haven't had any spare time lately so that's why I've been inactive on issues and the codebase.

The only reason there's no 1.9 build is because of some bugs I've been trying to sort out with the anchor point.

In regards to the actual post though, build your ship above water, then assemble.
