### ISSUE TITLE
Didn't this mod used to be called Archimedes Ships?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [darkevilmac/archimedes-ships-plus#99]

**Comment by exaskye** [comment]
Yes, it was previously called Archimedes Ships Plus. Darkevilmac renamed it to differentiate it from the original Archimedes Ships ~~as he was concerned people associate that name with a buggy mod, and because "Archimedes Ships" doesn't really make sense~~.

He's been working on making it a _lot_ less buggy, and I'll be working on a major system redesign in the future.

@Darkevilmac, feel free to weigh in and correct me if I'm wrong.

**Comment by P3rf3ctXZer0** [comment]
I loved that mod. Also its far more impressive to accept failures and mistakes than to hide them. Though I do really like the new name. I think he should warn users; "Previously Archimedes Ships" it respects veteran users like myself.

**Comment by exaskye** [comment]
~~I'd tend to agree. The rename wasn't really something we all (Elytra) agreed on, Darkevilmac did it because it's his mod and he felt it was the right choice, and as such I'll respect his decision. I'm fairly certain it actually started as a joke.~~

~~Changing the name on CurseForge to "Davinci's Vessels (formerly Archimedes Ships Plus)" would probably be good, but I don't have the authority to change the CurseForge page. On GitHub, the fork indicator is probably enough.~~

**Comment by darkevilmac** [comment]
The mod summary on curse states the name change. It was changed because people asked me to fix bugs with the original mod which is not in my power to do.
